### ISSUE TITLE
[ST] : 2022_04_30 회의 전 프로젝트 아이템

### ISSUE THREAD

**Issue by kangddong** [LetsSwifty/Swift_Bible#18]
일주일 간 고민한 아이템이 있으시면 공유 부탁드립니다.

1. 간단한 설명과 참고한 링크를 올리는 방법
2. 개인 아이템인 경우 
    화면 구성, 기술 구성에 대해서 기술해주세요!

**Comment by lii0730** [comment]
음 너무 막연하게 생각한걸수도 있긴 하지만

이미지 피커랑 테이블 뷰를 사용해서 슬라이드쇼 기능을 구현해보는걸 생각했어요!

1. 이미지 피커에서 슬라이드쇼에 사용할 이미지를 선택
2. 선택한 이미지를 테이블뷰에 표시
3. 시작 버튼을 누르면 슬라이드쇼 시작

[추가 기능]
1. 테이블 뷰 편집 모드를 사용해서 이미지 표출 순서 변경
2. 기타 등등...

**Comment by keenkim1202** [comment]
1.cell에 이미지와 타이틀, 편집버튼을 보여준다
2.cell의 편집버튼을 누르면 이미지와 타이틀을 추가 혹은 수정할 수 있다.
3.cell을 누르면 이미지와 타이틀이 크게 보이고, 좌우로 스와이프하여 이전 혹은 다음 이미지와 타이틀을 볼 수 있다.

이런 앱 생각해보았습니당!

**Comment by JINHYUNGP** [comment]
저는 개인 아이템으로 지금까지 배웠던걸 다양하게 사용해서 뮤비 플레이어를 만들어볼 생각입니다.
실제 동영상을 재생한다는 의미가 아니라  [https://www.youtube.com/watch?v=w-EoAXhKOLk](url) 의 화면처럼 화면을 터치하면 배경이 바뀌고 가사를 볼 수도 있게 만들 생각입니다.
1. 테이블 뷰에서 뮤비 선택 ( 하나만 만들예정이지만 배운거 쓴다는 느낌으로.._)
2. 설정화면으로 넘어가서 가사 키고 끔을 조절(다른 뷰컨트롤러 간의 데이터 전달)

**Comment by akatcn** [comment]
타임 트래킹 앱([ATracker 앱](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiF7Ofbo7v3AhVStVYBHSJVB5kQFnoECBQQAQ&url=https%3A%2F%2Fapps.apple.com%2Fus%2Fapp%2Fatracker-time-tracker%2Fid522008611&usg=AOvVaw2gbKCTaLQmKlja6LIfXVxy) 참조)
1. 테이블 뷰를 통한 항목 편집(셀을 탭하면 타임 트래킹 시작)
2. 로컬 알람 기능 & 현재 타이머 실행 정보를 알림센터에 표시
3. 측정된 데이터를 filtering 할 수 있어야 한다
4. MVC 패턴으로 제작
이 정도 고민 했습니다

**Comment by Diana-yjh** [comment]
간단한 개인 독서 기록 앱을 만들어 보려고 합니다.

> 1. 목록 페이지에서 도서 목록을 보여준다
> 2. 마이페이지에서 선택된 도서 목록을 확인할 수 있다.
> 3. 목록 페이지에서 마이페이지에 포함된 도서는 선택됨 표시를 한다.

**Comment by heejin342** [comment]
저는 메모 + Todolist 응용앱을 만들어볼까 합니다. 
강의를 여러개 쌓아두거나 블로그 글들, 혹은 구매할 것들을 맨날 크롬에 띄워놓기만 하고 잘 안보게됩니다.
해야할 일들도 맨날 카톡으로  하나씩 보내고 열어보지 않아서 결국엔 까먹어서 이런것들을 한번에 모을 수 있는 앱을 만들면 좋을 것 같아 고안하게 되었습니다.

1. segment control 을 통한 중요도 정리
2. 각 segment별 카테고리 화 (ex> 게임 동영상 , 공부, 살것, 해야할 것...)
3. 항목 입력시에는 타이틀, 링크, 알림시간, 이미지, 설명 등 기재
4. 일정 시간이 되면 notification 및 미룰 시간 설정
5. (미정) 껏다켜도 유지될 수 있도록 coreData 이용

**Comment by kangddong** [comment]
미리 알림(ToDo)과 메모 응용앱을 만들고 싶습니다.

공통
1. 미리 알림, 메모 프로토타입 셀 두개가 필요합니다
2. 작성 중 백그라운드로 일정시간 이상 머물게 되면 NotificationCenter를 통해 작성중인 미리 알림(할일), 메모가 있다고 알림해줍니다.

미리 알림(할일)
1. 하단에 텍스트필드, 시계아이콘, 추가 버튼을 통해 할일, 마감시간을 정합니다. (시간 선택 optional)
2. 테이블 셀 좌측에 버튼을 통해 완료시 ~strikethrough~
3. (미정) JSON File 생성 FileManager 사용하는 Todo, Memo의 save, load 부분은 싱글톤으로 구현
 메모 
1. 우측 상단에 + 버튼으로 메모VC 상세로 이동
2. 우측 상단 카메라 모양으로 image 삽입 가능 
3. 메모 작성 완료 후 우측 상단 저장 버튼
4. (미정) JSON File 생성 FileManager로 관리

희진님이랑 겹치는 부분이 많긴한데 따라한건 아닙니다아ㅏㅏ ㅜㅜ🥲

**Comment by heejin342** [comment]
ㅋㅋ 파일매니저 안써봤는데 좋아보이면 저도 바꾸겠습니다🤤
