### ISSUE TITLE
[Project] : dequeueReusableCell 사용에 관하여

### ISSUE THREAD

**Issue by JINHYUNGP** [LetsSwifty/Swift_Bible#21]
TableViewController인 VC1과 V2가 있습니다. VC2에서 BookIO(제가 만든 책 타입)로 생성된 데이터가 dataset(테이블 뷰 셀을 구성하는 리스트)에 들어간 것 까지는 확인했는데  cell을 dequeueReusableCell 을 하지 못하고 Unexpectedly found nil while unwrapping an Optional value 에러를 보입니다. 비슷한 기능을 하는 코드를 많이 찾아봤는데 왜 제 코드에서만 오류가 나는지 잘 모르겠어서 이슈올려봅니다!

    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let row = self.dataset[indexPath.row]
        if let cell = tableView.dequeueReusableCell(withIdentifier: "ListCell") as? BookCell{
        
        cell.title?.text = row.title
        cell.author?.text = row.author
        cell.desc?.text = row.description
        
        return cell
        } else {
            
            return UITableViewCell()
        }
    
    }



**Comment by keenkim1202** [comment]
```swift
    if let cell = tableView.dequeueReusableCell(withIdentifier: "ListCell"m for: indexPath) as? BookCell { ... }
```
로 작성해도 안되나요? 
근데 if let 으로 cell이 존재한다면 값을 넣어주는데 왜 `cell.title` 부분이 옵셔널인지 궁금합니다

**Comment by keenkim1202** [comment]
해당 이슈는 
`Identity Inspector > Restoration ID` 에 cell identifier를 넣어주어 생긴 이슈였습니다.
`Attributes Inspector`의 `identifier` 에 작성함으로써 해결되었습니다.

- Restoration ID : 어떤 view controller 혹은 view의 상태를 보존(preserve) 혹은 복원(restore)할 때 사용됩니다. [참고링크](https://developer.apple.com/library/archive/featuredarticles/ViewControllerPGforiPhoneOS/PreservingandRestoringState.html)
- identifier : 스토리보드에서 오브젝트를 instantiate 할 때 사용됩니다.
