### ISSUE TITLE
[iOS] : WebKit 이용한 WebView 구현 시 세션

### ISSUE THREAD

**Issue by mingging** [LetsSwifty/Swift_Bible#28]
안녕하세여 여러븐 제가 왔습니당~!

이번 챕터 11이 웹뷰 관련된 내용이라 제가 궁금했던 내용을 다같이 알아보는 것도 좋을 것 같아서 퀴즈로나마 가져왔어여~!

Q. 테이블뷰에 블로그 리스트가 있다. 각 셀을 클릭하면 해당 블로그가 웹뷰로 뜨게 된다. 
여기서 웹뷰 안에서 로그인을 한 후 다른 셀을 클릭해서 웹뷰가 뜰 경우 이 로그인은 유지가 될까?

이 내용은 사실 저는 답을 알고 있는데 그 답과 다른 결과가 나와서 다른 분들은 어떻게 뜨나 궁금해서 질문한 것도 있어여! 
(추가로 저 이거 면접때 질문 받았던 거였어요! 알아두면 좋을...지도..?)

**Comment by keenkim1202** [comment]
[WKWebView Persistent Storage of Cookies](https://stackoverflow.com/questions/39772007/wkwebview-persistent-storage-of-cookies)

참고자료로 남깁니다.
