### ISSUE TITLE
[iOS] : 'CHAPTER 08 - 8.5 테이블 뷰의 행 높이를 결정하는 방식'에서 오탈자 점검

### ISSUE THREAD

**Issue by akatcn** [LetsSwifty/Swift_Bible#8]
-567p 참고하시면 됩니다-
책에서는 `tableView(_:estimatedHeightForRowAt:)`에 대하여 안내하고 있는데, 정작 실습하는 코드(583p)에서는 이 메소드 대신에 `tableView(_:heightForRowAt:)`를 사용하고 있습니다. 실제로 `tableView(_:estimatedHeightForRowAt:)`으로 변경할 경우 의도대로 동작하지도 않거니와, 공식문서를 참조했을 때 책에서 안내한 내용과 더 적합한 메소드는 `tableView(_:heightForRowAt:)`인 것 같습니다
그래서 `tableView(_:estimatedHeightForRowAt:)`를 적어준 것이 오탈자라 판단하고는 있는데, 또 책에서는 너무 당당하게 `tableView(_:estimatedHeightForRowAt:)`라 계속 적혀있어서 제가 무언갈 놓친 것 같다는 불안감이 들기는 하네요... 이 파트 공부하신 다른분 의견은 어떠한지 궁금합니다!

**Comment by mingging** [comment]
오 저게 tableView Height 조정해 주는 메소드인걸루 알고 있는데 저 같은 경우도 heightForRowAt을 주로 쓰고 있습니당!
estimatedHeightForRowAt 이건 저도 써보진 않았는데 찾아보니까 reloadData 하고 나서 cell의 height가 튈때 height 복원해주는 용도로 쓰는 것 같네요!

책은 아직 안봐서 모르지만 .. 그렇다구 합니다! 아님 혹시 책에서 reloadData를 쓰고 있지는 않은지 봐야할 것 같네요!

**Comment by akatcn** [comment]
> 
책에서는 테이블 뷰 메소드를 호출하기 전에 reloadData()를 호출하고 있습니다! `tableView(_:estimatedHeightForRowAt:)`와의 관련성을 조금 더 살펴보겠습니다ㅋㅋ `tableView(_:estimatedHeightForRowAt:)` 메소드는 밍님도 자주 쓰는게 아니니 오탈자일 가능성이 조금더 커지는 느낌을 받습니다... 답변 감사합니다:)

**Comment by kangddong** [comment]
`tableView(_:estimatedHeightForRowAt:)` 
`TableView.estimatedRowHeight = UITableView.automaticDimension` 이런식을 셀 높이를 동적으로 할당할 때 주요 estimated가 사용되는데 이거랑 관련 된 메소드가 아닌가 싶습니다 ~

**Comment by kangddong** [comment]
셀마다 가변적인 컨텐츠를 표시를 할 때 `TableView.estimatedRowHeight` 로 대략적인 값을 주고 `UITableView.automaticDimension`이 xib, 혹은 스토리보드의 오토레이아웃 기준으로 자동으로 계산해주거든여

아마 `TableView.estimatedRowHeight` 메소드가 호출될 때 계산이 필요하다면 `tableView(_:estimatedHeightForRowAt:)` 메소드에서 추가적인 작업을 하지않을까싶네요

**Comment by kangddong** [comment]
의도대로 동적으로 셀이 변하지않는경우는 오토레이아웃 문제가 예상됩니다 ~

**Comment by akatcn** [comment]
> 의도대로 동적으로 셀이 변하지않는경우는 오토레이아웃 문제가 예상됩니다 ~

의견 감사합니다. 한 번 더 확인해보겠습니다!

**Comment by kangddong** [comment]
> > 의도대로 동적으로 셀이 변하지않는경우는 오토레이아웃 문제가 예상됩니다 ~
> 
> 의견 감사합니다. 한 번 더 확인해보겠습니다!

우와 reply 기능도 있네용 ㅎㅎ
