### ISSUE TITLE
[iOS] : CHAPTER 02 - 라이프 사이클과 상태변화

### ISSUE THREAD

**Issue by akatcn** [LetsSwifty/Swift_Bible#9]
책의 내용을 복습하면서 너무나 헷갈렸던 라이프 사이클, 상태 변화 개념을 나름 정리 해보았습니다.
이걸 여러분과 공유하고 싶기도 하고, 틀리거나 빠진 부분 점검을 받고 싶기도 해서 링크 올리게 되었습니다ㅋㅋ
보시고 문제있는 부분, 수정할 부분에 대한 지적이나 질문 등 피드백은 언제나 환영입니다! 아 물론 내용에 대한 토론 역시 환영입니다:)
감사합니다
[노션 링크](https://yonghooon.notion.site/UIKit-iOS-3094ed79459440328a2d54e2e4c95e7a)

**Comment by keenkim1202** [comment]
노션 안에서 댓글을 달아보고 싶었는데 권한이 없는 것 같아서 여기에 남깁니다ㅎㅎ 
iOS13 이전 버전 관련 부분에 
`AppDelegation.swift` -> `AppDelegate.swift`
로 오타가 난 것 같습니다!

**Comment by akatcn** [comment]
> 노션 안에서 댓글을 달아보고 싶었는데 권한이 없는 것 같아서 여기에 남깁니다ㅎㅎ
> iOS13 이전 버전 관련 부분에
> `AppDelegation.swift` -> `AppDelegate.swift`
> 로 오타가 난 것 같습니다!

앗 미처 발견하지 못했던 부분이었네요. 지적 감사합니다! 수정 완료하였고, 댓글 권한도 열어 놓았습니다ㅋㅋ
